"""VNE entry point.

This is the *only* place that orchestrates a full VNE deployment. The shell
wrapper at scripts/deploy.sh exists solely to call this module — it does not
contain logic.

Flow:
  1. Pre-flight: every required env var present? Halt with one combined error.
  2. Read + JSON-Schema-validate the VME manifest. (Hard fail if VME didn't
     succeed; we are not going to start configuring an unfinished host.)
  3. Read + Pydantic-validate velocitee.yml.
  4. Confirm the named provisioner is registered.
  5. Translate the user config into the internal VNEIntent.
  6. Build the renderer pipeline from the registry, run it.
  7. Run verify.py — gate. If anything fails here, do *not* write a manifest.
  8. Append the engines.vne record to the VME manifest and persist.

Path B (join existing network instead of provisioning a new OPNsense): not
implemented. Exit 1 with a clear message if requested.
"""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import jsonschema
import typer

# We are vne.deploy — we depend on the shared library and the local vne package.
from shared import manifest as mf
from shared import renderer_registry
from shared.cli import fatal, run_app, warn
from shared.pipeline import Pipeline
from shared.schema import VNEIntent

from vne import config as vne_config
from vne.scripts import verify as vne_verify

log = logging.getLogger("vne.deploy")

VNE_VERSION = "0.1.0"

_REPO_ROOT = Path(__file__).parent
_VME_MANIFEST_SCHEMA = _REPO_ROOT / "schema" / "vme-manifest.schema.json"
_VNE_MANIFEST_SCHEMA = _REPO_ROOT / "schema" / "vne-manifest.schema.json"

def _required_env_for(provisioner: str) -> list[str]:
    """Look up every required env var across the renderers a provisioner uses.

    Each renderer ships its own `config_keys` descriptor. Composite provisioners
    (e.g. opentofu+ansible) span multiple renderers; we union their required
    keys so pre-flight surfaces every miss in one error.
    """
    renderer_registry.ensure_loaded()
    if not renderer_registry.is_registered(provisioner):
        return []
    keys: list[str] = []
    seen: set[str] = set()
    for cls in renderer_registry.lookup(provisioner):
        for env in cls.required_env():
            if env not in seen:
                keys.append(env)
                seen.add(env)
    return keys


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

app = typer.Typer(
    name="vne",
    help="VNE — Velocitee Network Configuration Engine.",
    add_completion=False,
    context_settings={"help_option_names": ["-h", "--help"]},
    no_args_is_help=True,
)


@app.command()
def setup(
    manifest: Path = typer.Option(
        ..., "--manifest", "-m",
        help="Path to the VME handoff manifest. Used to pre-fill velocitee.yml.",
    ),
    config: Path = typer.Option(
        Path("velocitee.yml"), "--config", "-c",
        help="Where to write the velocitee.yml file.",
    ),
) -> None:
    """Bootstrap a velocitee.yml from a VME handoff manifest.

    Today this is a thin scaffold — it copies a starter velocitee.yml next to
    the user's working directory and points them at it. The interactive
    wizard that VME has for itself isn't ported to VNE yet.
    """
    if not manifest.exists():
        fatal(f"VME manifest not found: {manifest}")
    if config.exists():
        warn(f"{config} already exists — not overwriting")
        typer.echo(f"Edit {config}, then run: vne deploy --manifest {manifest}")
        return

    starter = (
        "# velocitee.yml — generated by `vne setup`\n"
        "# Fill in the values below, then run:\n"
        f"#   vne deploy --manifest {manifest}\n\n"
        "velocitee:\n"
        '  provisioner: "velocitee-native"\n\n'
        "vne:\n"
        '  wan_interface: "ens18"\n'
        '  lan_interface: "ens19"\n'
        '  opnsense_version: "24.7"\n'
        '  opnsense_iso_url: ""           # required\n'
        '  opnsense_iso_checksum: ""      # required: "sha256:<hex>"\n'
        "  vlans: []\n"
        "  dns:\n"
        '    upstream: ["1.1.1.1"]\n'
        '    domain: "lab.local"\n'
        "  firewall:\n"
        '    default_policy: "block"\n'
        "  opnsense_vm:\n"
        "    vmid: 100\n"
        "    cores: 2\n"
        "    memory_mb: 2048\n"
        "    disk_gb: 20\n"
        '    storage_pool: "local-lvm"\n'
    )
    config.write_text(starter)
    typer.echo(f"Wrote starter config: {config}")
    typer.echo(f"Edit it, then run: vne deploy --manifest {manifest}")


@app.command()
def deploy(
    config: Path = typer.Option(
        Path("velocitee.yml"), "--config", "-c",
        help="Path to velocitee.yml.",
    ),
    vme_manifest: Path = typer.Option(
        ..., "--manifest", "-m",
        help="Path to the VME handoff manifest written by `vme deploy`.",
    ),
    work_dir: Path = typer.Option(
        Path("vne/work"), "--work-dir",
        help="Where renderers stage rendered artifacts (HCL, inventory, …).",
    ),
    state_dir: Path = typer.Option(
        Path("vne/state"), "--state-dir",
        help="Renderer state files (vne.state.json) — survives between runs.",
    ),
    output: Path = typer.Option(
        Path("vne/output"), "--output",
        help="Where the final VNE manifest is written.",
    ),
    path_b: bool = typer.Option(
        False, "--join-existing",
        help="Path B: join an existing network instead of provisioning OPNsense. (Not implemented.)",
    ),
    verbose: bool = typer.Option(False, "--verbose", "-v"),
) -> None:
    """Provision and configure a network on top of a VME-provisioned host."""
    if path_b:
        typer.echo("Path B (join existing network) not yet implemented.", err=True)
        raise typer.Exit(1)

    logging.basicConfig(
        level=logging.DEBUG if verbose else logging.INFO,
        format="%(asctime)s [%(name)s] %(levelname)s %(message)s",
    )

    typer.echo("VNE — Velocitee Network Configuration Engine")
    typer.echo()

    # Step 1 — pre-flight env vars (driven by each renderer's config_keys)
    typer.echo("[1/7] Pre-flight: environment variables ...")
    file_cfg = _load_velocitee(config)
    provisioner = file_cfg.velocitee.provisioner
    expected = _required_env_for(provisioner)
    missing = [k for k in expected if not os.environ.get(k)]
    if missing:
        fatal(
            "missing required environment variables:\n  - " + "\n  - ".join(missing),
            hint="set them in your shell or a .envrc; never commit them.",
        )

    # Step 2 — VME manifest
    typer.echo("[2/7] Validating VME handoff manifest ...")
    vme_data = _load_and_validate_vme_manifest(vme_manifest)
    if vme_data["engines"].get("vme", {}).get("status") != "success":
        fatal(
            "VME manifest does not record a successful run — refusing to proceed.",
            hint=f"check {vme_manifest} or re-run vme deploy.",
        )

    # Step 3 — VNE config
    typer.echo("[3/7] Validating velocitee.yml VNE block ...")
    try:
        vne_config.validate_provisioner(provisioner)
    except vne_config.ConfigError as exc:
        fatal(str(exc))

    proxmox_host = vme_data["target"]["ip"]
    intent: VNEIntent = vne_config.to_intent(file_cfg, proxmox_host=proxmox_host)

    # Step 4 — build pipeline
    typer.echo(f"[4/7] Building renderer pipeline for provisioner '{provisioner}' ...")
    renderer_classes = renderer_registry.lookup(provisioner)
    renderers = []
    work_dir.mkdir(parents=True, exist_ok=True)
    state_dir.mkdir(parents=True, exist_ok=True)
    for cls in renderer_classes:
        renderers.append(cls(intent=intent, work_dir=work_dir, state_dir=state_dir))

    pipeline = Pipeline(renderers)

    # Step 5 — run
    started_at = datetime.now(timezone.utc)
    typer.echo("[5/7] Running pipeline ...")
    result = pipeline.run()

    if not result.success:
        fatal(
            f"pipeline failed: {result.failure_reason}",
            hint="state has been saved to vne/state/vne.state.json — re-running is safe (idempotent).",
        )

    # Step 6 — verify
    typer.echo("[6/7] Verification ...")
    opnsense_ip = result.aggregated_outputs.get("opnsense_ip")
    if not opnsense_ip:
        fatal("renderer pipeline did not return an opnsense_ip output; cannot verify.")

    api_key = (
        os.environ.get("OPNSENSE_API_KEY")
        or result.aggregated_outputs.get("opnsense_api_key")
    )
    api_secret = os.environ.get("OPNSENSE_API_SECRET")

    passed, _checks = vne_verify.run_all(
        opnsense_ip=opnsense_ip,
        expected_vlan_ids=[v.id for v in intent.network.vlans],
        api_key=api_key,
        api_secret=api_secret,
    )
    if not passed:
        fatal(
            "verification failed — VNE manifest WILL NOT be written.",
            hint="resolve the failure above and re-run; idempotency makes re-runs safe.",
        )

    # Step 7 — write output manifest
    typer.echo("[7/7] Writing VNE output manifest ...")
    completed_at = datetime.now(timezone.utc)

    extra = _build_vne_record(intent, result.aggregated_outputs, vme_data, provisioner)
    manifest = mf.append_engine(
        dict(vme_data),
        engine="vne",
        version=VNE_VERSION,
        started_at=started_at,
        completed_at=completed_at,
        extra=extra,
    )

    # Validate against the VNE-output schema *before* writing.
    _validate_against_vne_schema(manifest)

    output.mkdir(parents=True, exist_ok=True)
    out_path = mf.write(manifest, output)
    typer.echo(f"      wrote {out_path}")

    typer.echo()
    typer.echo("VNE complete. Hand off to VSE with:")
    typer.echo(f"  vse deploy --manifest {out_path}")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_velocitee(path: Path) -> vne_config.VelociteeFileConfig:
    try:
        return vne_config.load_file(path)
    except vne_config.ConfigError as exc:
        fatal(str(exc))


def _load_and_validate_vme_manifest(path: Path) -> dict[str, Any]:
    if not path.exists():
        fatal(
            f"VME manifest not found: {path}",
            hint="re-run vme deploy or pass the correct --manifest path.",
        )
    try:
        with open(path) as fh:
            data = json.load(fh)
    except json.JSONDecodeError as exc:
        fatal(f"VME manifest is not valid JSON: {exc}")

    schema = json.loads(_VME_MANIFEST_SCHEMA.read_text())
    validator = jsonschema.Draft7Validator(schema)
    errors = sorted(validator.iter_errors(data), key=lambda e: list(e.path))
    if errors:
        msg = "VME manifest failed schema validation:\n" + "\n".join(
            f"  - {'.'.join(str(p) for p in e.path) or '(root)'}: {e.message}"
            for e in errors
        )
        fatal(msg)
    return data


def _validate_against_vne_schema(manifest: dict[str, Any]) -> None:
    schema = json.loads(_VNE_MANIFEST_SCHEMA.read_text())
    validator = jsonschema.Draft7Validator(schema)
    errors = sorted(validator.iter_errors(manifest), key=lambda e: list(e.path))
    if errors:
        # This is internal: if it triggers, VNE wrote something its own schema
        # doesn't accept. Loud failure is correct.
        msg = "VNE output manifest failed self-validation:\n" + "\n".join(
            f"  - {'.'.join(str(p) for p in e.path) or '(root)'}: {e.message}"
            for e in errors
        )
        fatal(msg)


def _build_vne_record(
    intent: VNEIntent,
    outputs: dict[str, Any],
    vme_data: dict[str, Any],
    provisioner: str,
) -> dict[str, Any]:
    """Assemble the engines.vne entry for the output manifest."""
    return {
        "provisioner": provisioner,
        "opnsense": {
            "vm_ip": outputs.get("opnsense_ip", ""),
            "vmid": intent.opnsense.vm.vmid,
            "api_endpoint": outputs.get(
                "opnsense_api_endpoint", f"https://{outputs.get('opnsense_ip', '')}",
            ),
            "version": intent.opnsense.version,
        },
        "vlans": [
            {
                "id": v.id,
                "name": v.name,
                "cidr": v.cidr,
                "gateway": v.gateway,
                "dhcp_range": (
                    [v.dhcp_start, v.dhcp_end] if v.dhcp_start and v.dhcp_end else None
                ),
            }
            for v in intent.network.vlans
        ],
        "dns": {
            "server": outputs.get("opnsense_ip", ""),
            "domain": intent.network.dns.domain,
            "upstream": list(intent.network.dns.upstream),
        },
        "verification": {
            "passed": True,
            "checks": {
                "api_reachable": True,
                "dns_resolving": True,
                "internet_egress": True,
                "vlans_up": True,
            },
        },
        "proxmox_host": {
            "ip": vme_data["target"]["ip"],
            "hostname": vme_data["target"]["hostname"],
        },
    }


def main() -> None:
    run_app(app)


if __name__ == "__main__":
    main()
