#!/usr/bin/env python3
"""VME — Velocitee Metal Provisioning Engine CLI."""

from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path
from string import Template
from typing import Optional

import typer
import yaml

from . import preflight as pf
from . import manifest as mf
from . import images as img
from . import setup as wizard
from .os_registry import OS_REGISTRY, cached_entries

app = typer.Typer(
    name="vme",
    help="Velocitee Metal Provisioning Engine — PXE-boot and unattended OS install.",
    add_completion=False,
)
images_app = typer.Typer(help="Manage cached OS images.")
app.add_typer(images_app, name="images")

_CONFIG_DEFAULT = Path("vme-config.yml")
_REPO_ROOT = Path(__file__).parent.parent


# ---------------------------------------------------------------------------
# Config helpers
# ---------------------------------------------------------------------------


def _load_config(config_path: Path) -> dict:
    """Load and return the YAML config. Exits with a message on failure."""
    if not config_path.exists():
        typer.echo(
            f"[error] Config file not found: {config_path}\n"
            "Run 'vme setup' to create one.",
            err=True,
        )
        raise typer.Exit(1)
    try:
        with open(config_path) as fh:
            return yaml.safe_load(fh) or {}
    except yaml.YAMLError as exc:
        typer.echo(f"[error] Config file is not valid YAML: {exc}", err=True)
        raise typer.Exit(1)


def _print_preflight(report: pf.PreflightReport) -> None:
    """Pretty-print a preflight report."""
    typer.echo()
    for result in report.results:
        icon = "  [pass]" if result.passed else "  [FAIL]"
        typer.echo(f"{icon}  {result.name:<16} {result.detail}")
        if not result.passed and result.fix:
            for line in result.fix.splitlines():
                typer.echo(f"         fix: {line}")
    typer.echo()


# ---------------------------------------------------------------------------
# Network helpers
# ---------------------------------------------------------------------------


def _get_interface_ip(interface: str) -> Optional[str]:
    """Return the current IPv4 address on *interface*, or None."""
    try:
        result = subprocess.run(
            ["ip", "addr", "show", interface],
            capture_output=True, text=True, timeout=5,
        )
        m = re.search(r"inet (\d+\.\d+\.\d+\.\d+)/", result.stdout)
        return m.group(1) if m else None
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None


def _assign_ip(interface: str, ip: str) -> None:
    """Assign *ip*/24 to *interface* if it has no address yet."""
    existing = _get_interface_ip(interface)
    if existing:
        return
    typer.echo(f"  Assigning {ip}/24 to {interface} ...")
    result = subprocess.run(
        ["sudo", "ip", "addr", "add", f"{ip}/24", "dev", interface],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        typer.echo(
            f"[error] Could not assign IP to {interface}:\n{result.stderr}\n"
            f"Run manually: sudo ip addr add {ip}/24 dev {interface}",
            err=True,
        )
        raise typer.Exit(1)
    subprocess.run(["sudo", "ip", "link", "set", interface, "up"], capture_output=True)


# ---------------------------------------------------------------------------
# Boot script generation
# ---------------------------------------------------------------------------


def _generate_boot_ipxe(
    seed_ip: str,
    entries: list[tuple[str, str, str, Path]],
    default_slug: str,
) -> str:
    """Build a boot.ipxe script that only includes cached OSes in its menu.

    entries: list of (slug, menu_key, label, iso_path) from cached_entries()
    default_slug: OS slug to select automatically after the timeout
    """
    if not entries:
        # No images cached — show an error screen.
        return (
            "#!ipxe\n\n"
            f"set nginx http://{seed_ip}\n\n"
            "echo\n"
            "echo  No OS images are cached on the seed machine.\n"
            "echo  Run: vme images pull <os-name>\n"
            "echo\n"
            "prompt --timeout 30\n"
            "exit 1\n"
        )

    lines: list[str] = [
        "#!ipxe",
        "# Generated by vme deploy — do not edit by hand.",
        "",
        f"set nginx http://{seed_ip}",
        "",
        "echo",
        "echo  ============================================================",
        "echo   VME — Velocitee Metal Provisioning Engine",
        "echo   Seed:  ${nginx}",
        "echo   MAC:   ${net0/mac}",
        "echo  ============================================================",
        "echo",
        "",
        ":menu",
        "menu VME Provisioning Menu",
    ]

    # Determine default menu_key.
    default_key = entries[0][1]  # fallback: first cached OS
    for slug, key, label, _ in entries:
        if slug == default_slug:
            default_key = key
            break

    for _slug, key, label, _iso in entries:
        lines.append(f"item {key:<14} {label}")

    lines += [
        "item --gap --",
        "item exit           Exit (boot from local disk)",
        f"choose --default {default_key} --timeout 30 target || goto exit",
        "",
        "goto ${target}",
        "",
    ]

    for slug, key, label, iso in entries:
        lines += [
            f"# {'-' * 73}",
            f":{key}",
            f"echo Booting {label} ...",
            f"echo Image: ${{nginx}}/images/{iso.name}",
            "echo",
            f"sanboot --no-describe ${{nginx}}/images/{iso.name} || goto failed",
            "",
        ]

    lines += [
        "# ---------------------------------------------------------------------------",
        ":exit",
        "echo Exiting iPXE — attempting local disk boot.",
        "exit 0",
        "",
        ":failed",
        "echo",
        "echo Boot failed. Possible causes:",
        "echo   - Image not reachable at ${nginx}/images/",
        "echo   - Run: vme images list  (on the seed machine)",
        "echo",
        "echo Press any key to return to the menu.",
        "prompt --key s --timeout 10 || goto menu",
        "goto menu",
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Template rendering
# ---------------------------------------------------------------------------


def _render_templates(cfg: dict, run_dir: Path) -> None:
    """Render all config templates into *run_dir* before compose starts.

    boot.ipxe is generated dynamically from whatever ISOs are cached.
    All other templates (dnsmasq.conf, preseed files) use safe_substitute.
    """
    target = cfg.get("target", {})
    interface = cfg["provisioning_interface"]
    seed_ip = cfg.get("seed_ip") or _get_interface_ip(interface) or "192.168.100.1"
    os_name = target.get("os", "")

    # Generate boot.ipxe — only list OSes that are actually cached.
    cache_dir = img.cache_dir_for(cfg)
    entries = cached_entries(cache_dir)
    boot_ipxe = _generate_boot_ipxe(seed_ip, entries, default_slug=os_name)
    boot_ipxe_dest = run_dir / "ipxe" / "boot.ipxe"
    boot_ipxe_dest.parent.mkdir(parents=True, exist_ok=True)
    boot_ipxe_dest.write_text(boot_ipxe)

    # Render remaining templates via substitution.
    subs = {
        "PROVISIONING_INTERFACE": interface,
        "DHCP_RANGE_START": cfg["dhcp_range_start"],
        "DHCP_RANGE_END": cfg["dhcp_range_end"],
        "DHCP_LEASE_TIME": cfg.get("dhcp_lease_time", "12h"),
        "SEED_IP": seed_ip,
        "TARGET_HOSTNAME": target.get("hostname", "node-01"),
        "TARGET_DOMAIN": target.get("domain", "local"),
        "TARGET_IP": target.get("ip", ""),
        "TARGET_PREFIX": target.get("prefix", "24"),
        "TARGET_GATEWAY": target.get("gateway", ""),
        "TARGET_NETMASK": target.get("netmask", "255.255.255.0"),
        "TARGET_DNS": target.get("dns", "8.8.8.8"),
        "TARGET_DISK": target.get("disk", "/dev/sda"),
        "TARGET_NIC": "eth0",
        "TARGET_SSH_PUBLIC_KEY": target.get("ssh_public_key", ""),
        "TARGET_TIMEZONE": target.get("timezone", "UTC"),
        "TARGET_ROOT_PASSWORD": target.get("root_password", "changeme"),
        "TARGET_EMAIL": target.get("email", "root@localhost"),
        "TARGET_PASSWORD_HASH": target.get("password_hash", ""),
    }

    templates = {
        _REPO_ROOT / "seed" / "dnsmasq" / "dnsmasq.conf":   run_dir / "dnsmasq" / "dnsmasq.conf",
        _REPO_ROOT / "targets" / "proxmox" / "answer.toml": run_dir / "proxmox" / "answer.toml",
        _REPO_ROOT / "targets" / "ubuntu" / "preseed.cfg":  run_dir / "cloud-init" / "user-data",
        _REPO_ROOT / "targets" / "ubuntu" / "meta-data":    run_dir / "cloud-init" / "meta-data",
    }

    for src, dest in templates.items():
        if not src.exists():
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        rendered = Template(src.read_text()).safe_substitute(subs)
        dest.write_text(rendered)


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


@app.command()
def setup(
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c", help="Path to write vme-config.yml"),
) -> None:
    """Guided setup wizard — creates your config file interactively."""
    wizard.run(config)


@app.command()
def preflight(
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c", help="Path to vme-config.yml"),
) -> None:
    """Run pre-flight checks and report pass/fail without starting a deployment."""
    typer.echo("Running pre-flight checks ...")
    report = pf.run_all(config)
    _print_preflight(report)
    if report.passed:
        typer.echo("All checks passed. Ready to deploy.")
    else:
        typer.echo("[error] One or more checks failed. Fix the issues above before deploying.", err=True)
        raise typer.Exit(1)


@app.command()
def deploy(
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c", help="Path to vme-config.yml"),
    skip_preflight: bool = typer.Option(False, "--skip-preflight", help="Skip pre-flight checks (not recommended)."),
) -> None:
    """Deploy an OS to target hardware over PXE."""
    cfg = _load_config(config)

    if not skip_preflight:
        typer.echo("Running pre-flight checks ...")
        report = pf.run_all(config)
        _print_preflight(report)
        if not report.passed:
            typer.echo("[error] Pre-flight failed. Aborting deployment.", err=True)
            raise typer.Exit(1)
        typer.echo("Pre-flight passed.\n")

    # Ensure the provisioning interface has an IP.
    interface = cfg.get("provisioning_interface", "")
    seed_ip = cfg.get("seed_ip", "192.168.100.1")
    if interface:
        _assign_ip(interface, seed_ip)

    # Download / verify the configured OS image.
    os_name: str = cfg.get("target", {}).get("os", "")
    typer.echo(f"Ensuring {os_name} image is cached ...")
    try:
        iso_path = img.ensure_image(os_name, cfg)
        typer.echo(f"  Image ready: {iso_path.name}\n")
    except (RuntimeError, ValueError) as exc:
        typer.echo(f"[error] {exc}", err=True)
        raise typer.Exit(1)

    # Render all config templates into ./run/ before compose starts.
    run_dir = config.parent / "run"
    typer.echo("Preparing seed stack config ...")
    _render_templates(cfg, run_dir)

    typer.echo("Starting seed stack ...")
    _run_compose(cfg, config.parent, up=True)

    typer.echo("\nSeed stack is running.")
    typer.echo("Power on the target machine now. It will PXE boot and install automatically.")
    typer.echo("Press Ctrl+C here when provisioning is complete to stop the seed stack.\n")

    try:
        _compose_logs(config.parent)
    except KeyboardInterrupt:
        typer.echo("\nStopping seed stack ...")
        _run_compose(cfg, config.parent, up=False)
        typer.echo("Done.")


@app.command()
def status(
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c", help="Path to vme-config.yml"),
) -> None:
    """Show the current state of the seed stack."""
    result = subprocess.run(
        ["docker", "compose", "ps"],
        cwd=config.parent,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        typer.echo("[error] Could not query Docker Compose status.", err=True)
        typer.echo(result.stderr, err=True)
        raise typer.Exit(1)
    typer.echo(result.stdout)


@app.command()
def reset(
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c", help="Path to vme-config.yml"),
    include_images: bool = typer.Option(False, "--images", help="Also delete cached OS images."),
    yes: bool = typer.Option(False, "--yes", "-y", help="Skip confirmation prompt."),
) -> None:
    """Tear down all VME state and return to a clean install.

    Stops the seed stack, removes Docker volumes and the built iPXE image,
    and clears the rendered run/ directory. Pass --images to also delete
    cached OS ISOs (requires re-downloading on next deploy).
    """
    cwd = config.parent

    parts = [
        "seed stack containers and volumes",
        "built iPXE Docker image",
        "rendered run/ config",
    ]
    if include_images:
        parts.append("cached OS images")

    if not yes:
        typer.echo("This will remove:")
        for p in parts:
            typer.echo(f"  • {p}")
        typer.echo()
        typer.confirm("Continue?", abort=True)

    # Stop containers and remove volumes.
    typer.echo("Stopping seed stack ...")
    subprocess.run(
        ["docker", "compose", "down", "--volumes"],
        cwd=cwd, capture_output=True,
    )

    # Remove the compiled iPXE Docker image so next deploy rebuilds it.
    typer.echo("Removing built Docker image ...")
    subprocess.run(["docker", "rmi", "vme-ipxe-build"], capture_output=True)

    # Clear rendered run/ directory.
    run_dir = cwd / "run"
    if run_dir.exists():
        typer.echo("Clearing run/ ...")
        shutil.rmtree(run_dir)

    # Optionally clear image cache.
    if include_images:
        if config.exists():
            cfg = _load_config(config)
            removed = img.clean_cache(cfg)
            typer.echo(f"Removed {removed} cached image file(s).")
        else:
            typer.echo("No config found — skipping image cache cleanup.")

    typer.echo("\nReset complete. Run 'vme deploy' to start fresh.")


# ---------------------------------------------------------------------------
# Images subcommands
# ---------------------------------------------------------------------------


@images_app.command("list")
def images_list(
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c", help="Path to vme-config.yml"),
) -> None:
    """List cached OS images."""
    cfg = _load_config(config)
    cached = img.list_cached(cfg)
    if not cached:
        typer.echo("No images cached yet. Run 'vme images pull <os>' to download.")
        typer.echo(f"  Available: {', '.join(OS_REGISTRY)}")
        return
    typer.echo(f"  {'OS':<16} {'Filename':<46} {'Size':>10}")
    typer.echo("  " + "-" * 74)
    for entry in cached:
        typer.echo(f"  {entry['os']:<16} {entry['filename']:<46} {entry['size_mb']:>9.1f} MB")


@images_app.command("pull")
def images_pull(
    os_name: Optional[str] = typer.Argument(None, help="OS slug to cache (e.g. ubuntu-server). Defaults to configured OS."),
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c", help="Path to vme-config.yml"),
) -> None:
    """Pre-cache an OS image before deployment.

    Available OS slugs: {slugs}
    """
    cfg = _load_config(config)
    if os_name is None:
        os_name = cfg.get("target", {}).get("os", "")
        if not os_name:
            typer.echo("[error] No OS specified and none configured in vme-config.yml.", err=True)
            raise typer.Exit(1)
    typer.echo(f"Pulling {os_name} image ...")
    try:
        dest = img.ensure_image(os_name, cfg)
        typer.echo(f"Cached: {dest}")
    except (RuntimeError, ValueError) as exc:
        typer.echo(f"[error] {exc}", err=True)
        raise typer.Exit(1)


images_pull.__doc__ = images_pull.__doc__.format(slugs=", ".join(OS_REGISTRY))  # type: ignore[union-attr]


@images_app.command("clean")
def images_clean(
    os_name: Optional[str] = typer.Argument(None, help="OS slug to remove (e.g. proxmox-ve). Omit to remove all."),
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c", help="Path to vme-config.yml"),
    yes: bool = typer.Option(False, "--yes", "-y", help="Skip confirmation prompt."),
) -> None:
    """Delete cached OS images.

    Pass an OS slug to delete only that OS. Omit to delete everything.
    """
    cfg = _load_config(config)
    cache = img.cache_dir_for(cfg)

    target_desc = f"'{os_name}' images" if os_name else f"all images"
    if not yes:
        typer.confirm(f"Delete {target_desc} in {cache}?", abort=True)

    try:
        removed = img.clean_cache(cfg, os_name=os_name)
    except ValueError as exc:
        typer.echo(f"[error] {exc}", err=True)
        raise typer.Exit(1)

    typer.echo(f"Removed {removed} file(s).")


# ---------------------------------------------------------------------------
# Docker Compose helpers
# ---------------------------------------------------------------------------


def _run_compose(cfg: dict, cwd: Path, *, up: bool) -> None:
    """Start or stop the Docker Compose seed stack, passing required env vars."""
    interface = cfg.get("provisioning_interface", "")
    seed_ip = cfg.get("seed_ip") or _get_interface_ip(interface) or "192.168.100.1"
    cache_dir = str(img.cache_dir_for(cfg))

    env_vars = {
        "PROVISIONING_INTERFACE": interface,
        "DHCP_RANGE_START": str(cfg.get("dhcp_range_start", "")),
        "DHCP_RANGE_END": str(cfg.get("dhcp_range_end", "")),
        "DHCP_LEASE_TIME": str(cfg.get("dhcp_lease_time", "12h")),
        "SEED_IP": seed_ip,
        "IMAGE_CACHE_DIR": cache_dir,
    }

    compose_env = {**os.environ, **env_vars}

    if up:
        cmd = ["docker", "compose", "up", "-d", "--build"]
    else:
        cmd = ["docker", "compose", "down"]

    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, env=compose_env)
    if result.returncode != 0:
        typer.echo(f"[error] docker compose failed:\n{result.stderr}", err=True)
        raise typer.Exit(1)


def _compose_logs(cwd: Path) -> None:
    """Tail Docker Compose logs (blocks until interrupted)."""
    subprocess.run(["docker", "compose", "logs", "-f"], cwd=cwd)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    """CLI entry point."""
    app()


if __name__ == "__main__":
    main()
