#!/usr/bin/env python3
"""VME — Velocitee Metal Provisioning Engine CLI."""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from string import Template
from typing import Optional

import typer
import yaml

from . import preflight as pf
from . import manifest as mf
from . import images as img
from . import setup as wizard
from .os_registry import OS_REGISTRY, cached_entries

app = typer.Typer(
    name="vme",
    help="Velocitee Metal Provisioning Engine — PXE-boot and unattended OS install.",
    add_completion=False,
)
images_app = typer.Typer(help="Manage cached OS images.")
app.add_typer(images_app, name="images")

_CONFIG_DEFAULT  = Path("vme-config.yml")
_REPO_ROOT       = Path(__file__).parent.parent
_LOG_DIR         = Path("~/.velocitee/logs").expanduser()
_MANIFEST_OUTDIR = _REPO_ROOT / "manifests" / "output"

_LINE = "═" * 60


def _load_config(config_path: Path) -> dict:
    if not config_path.exists():
        typer.echo(
            f"[error] Config file not found: {config_path}\n"
            "Run 'vme setup' to create one.",
            err=True,
        )
        raise typer.Exit(1)
    try:
        with open(config_path) as fh:
            return yaml.safe_load(fh) or {}
    except yaml.YAMLError as exc:
        typer.echo(f"[error] Config file is not valid YAML: {exc}", err=True)
        raise typer.Exit(1)


def _print_preflight(report: pf.PreflightReport) -> None:
    typer.echo()
    for result in report.results:
        icon = "  [pass]" if result.passed else "  [FAIL]"
        typer.echo(f"{icon}  {result.name:<16} {result.detail}")
        if not result.passed and result.fix:
            for line in result.fix.splitlines():
                typer.echo(f"         fix: {line}")
    typer.echo()


def _get_interface_ip(interface: str) -> Optional[str]:
    try:
        result = subprocess.run(
            ["ip", "addr", "show", interface],
            capture_output=True, text=True, timeout=5,
        )
        m = re.search(r"inet (\d+\.\d+\.\d+\.\d+)/", result.stdout)
        return m.group(1) if m else None
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None


def _assign_ip(interface: str, ip: str) -> None:
    if _get_interface_ip(interface):
        return
    typer.echo(f"  Assigning {ip}/24 to {interface} ...")
    result = subprocess.run(
        ["sudo", "ip", "addr", "add", f"{ip}/24", "dev", interface],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        typer.echo(
            f"[error] Could not assign IP to {interface}:\n{result.stderr}\n"
            f"Run manually: sudo ip addr add {ip}/24 dev {interface}",
            err=True,
        )
        raise typer.Exit(1)
    subprocess.run(["sudo", "ip", "link", "set", interface, "up"], capture_output=True)


def _generate_boot_ipxe(
    seed_ip: str,
    entries: list[tuple[str, str, str, Path]],
    default_slug: str,
) -> str:
    if not entries:
        return (
            "#!ipxe\n\n"
            f"set nginx http://{seed_ip}\n\n"
            "echo\necho  No OS images are cached on the seed machine.\n"
            "echo  Run: vme images pull <os-name>\n"
            "echo\nprompt --timeout 30\nexit 1\n"
        )

    lines: list[str] = [
        "#!ipxe",
        "# Generated by vme deploy — do not edit by hand.",
        "",
        f"set nginx http://{seed_ip}",
        "",
        "echo",
        "echo  ============================================================",
        "echo   VME — Velocitee Metal Provisioning Engine",
        "echo   Seed:  ${nginx}",
        "echo   MAC:   ${net0/mac}",
        "echo  ============================================================",
        "echo",
        "",
        ":menu",
        "menu VME Provisioning Menu",
    ]

    default_key = entries[0][1]
    for slug, key, label, _ in entries:
        if slug == default_slug:
            default_key = key
            break

    for _slug, key, label, _iso in entries:
        lines.append(f"item {key:<14} {label}")

    lines += [
        "item --gap --",
        "item exit           Exit (boot from local disk)",
        f"choose --default {default_key} --timeout 30 target || goto exit",
        "",
        "goto ${target}",
        "",
    ]

    for slug, key, label, iso in entries:
        meta = OS_REGISTRY.get(slug, {})
        boot_method = meta.get("boot_method", "sanboot")

        if boot_method == "kernel":
            # Boot vmlinuz + initrd directly so we can pass url= and autoinstall params.
            # The url= kernel arg tells the live initrd where to find the ISO (its squashfs root).
            # ds=nocloud-net;s= tells cloud-init where to find user-data / meta-data.
            lines += [
                f":{key}",
                f"echo Booting {label} ...",
                f"kernel ${{nginx}}/boot/{slug}/vmlinuz",
                f"initrd ${{nginx}}/boot/{slug}/initrd",
                (
                    f"imgargs vmlinuz initrd=initrd ip=dhcp"
                    f" url=${{nginx}}/images/{iso.name}"
                    f" autoinstall ds=nocloud-net;s=${{nginx}}/cloud-init/"
                ),
                "boot || goto failed",
                "",
            ]
        else:
            lines += [
                f":{key}",
                f"echo Booting {label} ...",
                f"echo Image: ${{nginx}}/images/{iso.name}",
                "echo",
                f"sanboot --no-describe ${{nginx}}/images/{iso.name} || goto failed",
                "",
            ]

    lines += [
        ":exit",
        "echo Exiting iPXE — attempting local disk boot.",
        "exit 0",
        "",
        ":failed",
        "echo",
        "echo Boot failed. Possible causes:",
        "echo   - Image not reachable at ${nginx}/images/",
        "echo   - Run: vme images list  (on the seed machine)",
        "echo",
        "echo Press any key to return to the menu.",
        "prompt --key s --timeout 10 || goto menu",
        "goto menu",
        "",
    ]

    return "\n".join(lines)


def _extract_boot_files(iso_path: Path, boot_dir: Path, slug: str) -> None:
    """Mount an ISO and copy the kernel + initrd into boot_dir/slug/.

    Ubuntu's live initrd needs to be booted directly (not via sanboot) so we
    can pass url= and autoinstall params on the kernel cmdline. This extracts
    the right files from the ISO at deploy time.
    """
    meta = OS_REGISTRY.get(slug, {})
    kernel_rel = meta.get("kernel_path", "casper/vmlinuz")
    initrd_rel  = meta.get("initrd_path", "casper/initrd")

    dest = boot_dir / slug
    vmlinuz = dest / "vmlinuz"
    initrd  = dest / "initrd"

    if vmlinuz.exists() and initrd.exists():
        return  # already extracted from a previous run

    dest.mkdir(parents=True, exist_ok=True)
    mnt = Path("/tmp/vme-iso-mount")
    mnt.mkdir(exist_ok=True)

    typer.echo(f"  Extracting boot files from {iso_path.name} ...")
    try:
        result = subprocess.run(
            ["sudo", "mount", "-o", "loop,ro", str(iso_path), str(mnt)],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(f"Could not mount ISO: {result.stderr.strip()}")

        src_vmlinuz = mnt / kernel_rel
        src_initrd  = mnt / initrd_rel
        if not src_vmlinuz.exists() or not src_initrd.exists():
            raise RuntimeError(
                f"Expected {kernel_rel} and {initrd_rel} inside the ISO but couldn't find them."
            )

        shutil.copy2(src_vmlinuz, vmlinuz)
        shutil.copy2(src_initrd, initrd)
        typer.echo(f"  Boot files extracted ({vmlinuz.stat().st_size // (1024**2)} MB kernel, "
                   f"{initrd.stat().st_size // (1024**2)} MB initrd).")
    finally:
        subprocess.run(["sudo", "umount", str(mnt)], capture_output=True)


def _render_templates(cfg: dict, run_dir: Path) -> None:
    target    = cfg.get("target", {})
    interface = cfg["provisioning_interface"]
    seed_ip   = cfg.get("seed_ip") or _get_interface_ip(interface) or "192.168.100.1"
    os_name   = target.get("os", "")

    cache_dir = img.cache_dir_for(cfg)
    entries   = cached_entries(cache_dir)

    # For OSes that boot via kernel+initrd, extract those files from the ISO now
    # so nginx can serve them. The mount point needs sudo because loop devices do.
    boot_dir = run_dir / "boot"
    for slug, _key, _label, iso_path in entries:
        meta = OS_REGISTRY.get(slug, {})
        if meta.get("boot_method") == "kernel":
            _extract_boot_files(iso_path, boot_dir, slug)

    boot_ipxe = _generate_boot_ipxe(seed_ip, entries, default_slug=os_name)
    boot_dest = run_dir / "ipxe" / "boot.ipxe"
    boot_dest.parent.mkdir(parents=True, exist_ok=True)
    boot_dest.write_text(boot_ipxe)

    subs = {
        "PROVISIONING_INTERFACE": interface,
        "DHCP_RANGE_START":       cfg["dhcp_range_start"],
        "DHCP_RANGE_END":         cfg["dhcp_range_end"],
        "DHCP_LEASE_TIME":        cfg.get("dhcp_lease_time", "12h"),
        "SEED_IP":                seed_ip,
        "TARGET_HOSTNAME":        target.get("hostname", "node-01"),
        "TARGET_DOMAIN":          target.get("domain", "local"),
        "TARGET_IP":              target.get("ip", ""),
        "TARGET_PREFIX":          target.get("prefix", "24"),
        "TARGET_GATEWAY":         target.get("gateway", ""),
        "TARGET_NETMASK":         target.get("netmask", "255.255.255.0"),
        "TARGET_DNS":             target.get("dns", "8.8.8.8"),
        "TARGET_DISK":            target.get("disk", "/dev/sda"),
        "TARGET_NIC":             "eth0",
        "TARGET_TIMEZONE":        target.get("timezone", "UTC"),
        "TARGET_SSH_PUBLIC_KEY":  target.get("ssh_public_key", ""),
        "TARGET_ROOT_PASSWORD":   target.get("root_password", "changeme"),
        "TARGET_EMAIL":           target.get("email", "root@localhost"),
        "TARGET_PASSWORD_HASH":   target.get("password_hash", ""),
    }

    templates = {
        _REPO_ROOT / "seed" / "dnsmasq" / "dnsmasq.conf":   run_dir / "dnsmasq" / "dnsmasq.conf",
        _REPO_ROOT / "targets" / "proxmox" / "answer.toml": run_dir / "proxmox" / "answer.toml",
        _REPO_ROOT / "targets" / "ubuntu" / "preseed.cfg":  run_dir / "cloud-init" / "user-data",
        _REPO_ROOT / "targets" / "ubuntu" / "meta-data":    run_dir / "cloud-init" / "meta-data",
    }

    for src, dest in templates.items():
        if not src.exists():
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(Template(src.read_text()).safe_substitute(subs))


# Events to surface in normal (non-verbose) mode.
# Each entry: (regex, display_template, deduplicate)
# display_template may reference named groups from the regex.
_LOG_EVENTS = [
    (re.compile(r'DHCPDISCOVER\(\S+\)\s+([\da-fA-F:]{17})'),
     "Target discovered       MAC {1}", True),
    (re.compile(r'DHCPACK\(\S+\)\s+(\d+\.\d+\.\d+\.\d+)\s+([\da-fA-F:]{17})'),
     "DHCP lease granted      {1}  ({2})", True),
    (re.compile(r'sent /tftp/undionly\.kpxe'),
     "iPXE binary delivered   via TFTP", True),
    (re.compile(r'"GET /ipxe/boot\.ipxe[^"]*" 200'),
     "Boot menu loaded        via HTTP", True),
    (re.compile(r'"GET /images/([^"]+\.iso)[^"]*" 206'),
     "OS image streaming      {1}", True),
    (re.compile(r'vme-provision-complete'),
     None, False),  # handled specially — not printed here
]


def _format_event(pattern: re.Pattern, template: str, line: str) -> str | None:
    m = pattern.search(line)
    if not m:
        return None
    result = template
    for i, g in enumerate(m.groups(), 1):
        result = result.replace(f"{{{i}}}", g or "")
    return result


def _fmt_duration(seconds: float) -> str:
    m, s = divmod(int(seconds), 60)
    return f"{m}m {s:02d}s" if m else f"{s}s"


def _stream_deploy_logs(
    cwd: Path,
    log_path: Path,
    verbose: bool,
) -> tuple[bool, str | None]:
    """Stream compose logs. Returns (completed, mac_address).

    Normal mode: show one line per key milestone, suppress noise.
    Verbose mode: pass everything through.
    Full logs always written to log_path for troubleshooting.
    """
    proc = subprocess.Popen(
        ["docker", "compose", "logs", "-f", "--no-color"],
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )

    log_path.parent.mkdir(parents=True, exist_ok=True)
    completed  = False
    mac        = None
    shown: set[str] = set()

    try:
        with open(log_path, "w") as log_fh:
            for raw in proc.stdout:
                log_fh.write(raw)
                log_fh.flush()

                if verbose:
                    sys.stdout.write(raw)
                    sys.stdout.flush()
                else:
                    line = raw.strip()
                    ts   = datetime.now().strftime("%H:%M:%S")

                    for pattern, template, dedup in _LOG_EVENTS:
                        if not pattern.search(line):
                            continue
                        if template is None:
                            break
                        msg = _format_event(pattern, template, line)
                        if msg:
                            key = msg[:40]
                            if dedup and key in shown:
                                break
                            shown.add(key)
                            typer.echo(f"  [{ts}]  {msg}")
                            # Capture MAC from DHCPACK line
                            if "DHCP lease" in msg:
                                m2 = re.search(r'\(([\da-fA-F:]{17})\)', msg)
                                if m2:
                                    mac = m2.group(1)
                        break

                # Completion signal — stop regardless of mode
                if "vme-provision-complete" in raw:
                    completed = True
                    break

    except KeyboardInterrupt:
        pass
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()

    return completed, mac


def _print_summary(
    cfg: dict,
    iso_path: Path,
    started_at: datetime,
    completed_at: datetime,
    manifest_path: Path,
    mac: str | None,
) -> None:
    target   = cfg.get("target", {})
    hostname = target.get("hostname", "")
    ip       = target.get("ip", "")
    os_name  = target.get("os", "")
    username = "root" if os_name == "proxmox-ve" else "ubuntu"
    duration = _fmt_duration((completed_at - started_at).total_seconds())

    typer.echo()
    typer.echo(_LINE)
    typer.echo(f"  Provisioning complete.")
    typer.echo()
    typer.echo(f"  Hostname:   {hostname}")
    typer.echo(f"  OS:         {iso_path.stem}")
    if mac:
        typer.echo(f"  MAC:        {mac}")
    typer.echo(f"  IP:         {ip}")
    typer.echo(f"  SSH user:   {username}")
    typer.echo(f"  Duration:   {duration}")
    typer.echo(f"  Manifest:   {manifest_path}")
    typer.echo(f"  Full logs:  {_LOG_DIR / manifest_path.stem}.log")
    typer.echo()
    typer.echo("  The machine has powered off.")
    typer.echo("  Before powering it on, fix the boot order so it boots from disk:")
    typer.echo()
    typer.echo("    VMware:        VM → Settings → Options → Boot → Hard Disk first")
    typer.echo("    Real hardware: Enter BIOS (F2 / Del / F12) → Boot Order → Hard Disk first")
    typer.echo()
    typer.echo("  Once booted:")
    typer.echo(f"    ssh {username}@{ip}")
    typer.echo(_LINE)


def _prompt_next_engine(manifest_path: Path) -> None:
    """Ask whether to hand off to VNE. Handles VNE not being installed."""
    typer.echo()
    typer.echo("  What next?")
    typer.echo("    [1]  Continue to VNE — configure networking")
    typer.echo("    [2]  Done — I'll connect manually or run other engines later")
    typer.echo()

    try:
        choice = input("  Choice [2]: ").strip() or "2"
    except (KeyboardInterrupt, EOFError):
        choice = "2"

    if choice != "1":
        typer.echo()
        typer.echo(f"  Manifest saved. Pass it to any engine with:")
        typer.echo(f"    vne setup --manifest {manifest_path}")
        typer.echo()
        return

    # Check if VNE is installed.
    if shutil.which("vne"):
        typer.echo()
        typer.echo("  Handing off to VNE ...")
        subprocess.run(["vne", "setup", "--manifest", str(manifest_path)])
    else:
        typer.echo()
        typer.echo("  VNE is not installed on this machine.")
        typer.echo("  To install VNE on the seed machine:")
        typer.echo("    curl -fsSL https://raw.githubusercontent.com/velocit-ee/core/main/vne/install.sh | bash")
        typer.echo()
        typer.echo(f"  Then run:")
        typer.echo(f"    vne setup --manifest {manifest_path}")
        typer.echo()


@app.command()
def setup(
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c", help="Path to write vme-config.yml"),
) -> None:
    """Guided setup wizard — creates your config file interactively."""
    wizard.run(config)


@app.command()
def preflight(
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c", help="Path to vme-config.yml"),
) -> None:
    """Run pre-flight checks without starting a deployment."""
    typer.echo("Running pre-flight checks ...")
    report = pf.run_all(config)
    _print_preflight(report)
    if report.passed:
        typer.echo("All checks passed. Ready to deploy.")
    else:
        typer.echo("[error] One or more checks failed.", err=True)
        raise typer.Exit(1)


@app.command()
def deploy(
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c", help="Path to vme-config.yml"),
    skip_preflight: bool = typer.Option(False, "--skip-preflight", help="Skip pre-flight checks."),
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Show full compose logs instead of filtered events."),
) -> None:
    """Provision a machine over PXE — runs unattended from power-on to shutdown."""
    cfg = _load_config(config)

    if not skip_preflight:
        typer.echo("Running pre-flight checks ...")
        report = pf.run_all(config)
        _print_preflight(report)
        if not report.passed:
            typer.echo("[error] Pre-flight failed. Aborting.", err=True)
            raise typer.Exit(1)
        typer.echo("Pre-flight passed.\n")

    interface = cfg.get("provisioning_interface", "")
    seed_ip   = cfg.get("seed_ip", "192.168.100.1")
    if interface:
        _assign_ip(interface, seed_ip)

    os_name: str = cfg.get("target", {}).get("os", "")
    typer.echo(f"Ensuring {os_name} image is cached ...")
    try:
        iso_path = img.ensure_image(os_name, cfg)
        typer.echo(f"  Image ready: {iso_path.name}\n")
    except (RuntimeError, ValueError) as exc:
        typer.echo(f"[error] {exc}", err=True)
        raise typer.Exit(1)

    run_dir = config.parent / "run"
    typer.echo("Preparing seed stack config ...")
    _render_templates(cfg, run_dir)

    typer.echo("Starting seed stack ...")
    _run_compose(cfg, config.parent, up=True)

    started_at = datetime.now(timezone.utc)
    hostname   = cfg.get("target", {}).get("hostname", "target")
    ts_label   = started_at.strftime("%Y%m%dT%H%M%SZ")
    log_path   = _LOG_DIR / f"deploy-{hostname}-{ts_label}.log"

    typer.echo()
    typer.echo(_LINE)
    typer.echo("  Seed stack is running.")
    typer.echo("  Power on the target machine now.")
    if verbose:
        typer.echo("  Showing full compose logs. Press Ctrl+C to stop.\n")
    else:
        typer.echo(f"  Watching for key events. Full logs → {log_path}")
        typer.echo("  Press Ctrl+C to stop manually.\n")

    completed, mac = _stream_deploy_logs(config.parent, log_path, verbose=verbose)

    completed_at = datetime.now(timezone.utc)

    typer.echo()
    typer.echo("Stopping seed stack ...")
    _run_compose(cfg, config.parent, up=False)

    if not completed:
        typer.echo("\nSeed stack stopped. Provisioning may not have completed.")
        typer.echo(f"Check the full logs at: {log_path}")
        raise typer.Exit(0)

    # Write manifest.
    try:
        manifest = mf.build_vme(
            cfg=cfg,
            iso_path=iso_path,
            mac=mac,
            started_at=started_at,
            completed_at=completed_at,
        )
        manifest_path = mf.write(manifest, _MANIFEST_OUTDIR)
    except (ValueError, Exception) as exc:
        typer.echo(f"[warn] Could not write manifest: {exc}", err=True)
        manifest_path = Path("(not written)")

    _print_summary(cfg, iso_path, started_at, completed_at, manifest_path, mac)
    _prompt_next_engine(manifest_path)


@app.command()
def status(
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c", help="Path to vme-config.yml"),
) -> None:
    """Show the current state of the seed stack."""
    result = subprocess.run(
        ["docker", "compose", "ps"],
        cwd=config.parent, capture_output=True, text=True,
    )
    if result.returncode != 0:
        typer.echo("[error] Could not query Docker Compose status.", err=True)
        raise typer.Exit(1)
    typer.echo(result.stdout)


@app.command()
def reset(
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c", help="Path to vme-config.yml"),
    include_images: bool = typer.Option(False, "--images", help="Also delete cached OS images."),
    yes: bool = typer.Option(False, "--yes", "-y", help="Skip confirmation."),
) -> None:
    """Tear down all VME state and return to a clean install."""
    cwd   = config.parent
    parts = ["seed stack containers and volumes", "built iPXE Docker image", "rendered run/ config"]
    if include_images:
        parts.append("cached OS images")

    if not yes:
        typer.echo("This will remove:")
        for p in parts:
            typer.echo(f"  • {p}")
        typer.echo()
        typer.confirm("Continue?", abort=True)

    typer.echo("Stopping seed stack ...")
    subprocess.run(["docker", "compose", "down", "--volumes"], cwd=cwd, capture_output=True)

    typer.echo("Removing built Docker image ...")
    subprocess.run(["docker", "rmi", "vme-ipxe-build"], capture_output=True)

    run_dir = cwd / "run"
    if run_dir.exists():
        typer.echo("Clearing run/ ...")
        shutil.rmtree(run_dir)

    if include_images and config.exists():
        removed = img.clean_cache(_load_config(config))
        typer.echo(f"Removed {removed} cached image file(s).")

    typer.echo("\nReset complete. Run 'vme deploy' to start fresh.")


@images_app.command("list")
def images_list(
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c"),
) -> None:
    """List cached OS images."""
    cfg    = _load_config(config)
    cached = img.list_cached(cfg)
    if not cached:
        typer.echo("No images cached yet. Run 'vme images pull <os>' to download.")
        typer.echo(f"  Available: {', '.join(OS_REGISTRY)}")
        return
    typer.echo(f"  {'OS':<16} {'Filename':<46} {'Size':>10}")
    typer.echo("  " + "-" * 74)
    for entry in cached:
        typer.echo(f"  {entry['os']:<16} {entry['filename']:<46} {entry['size_mb']:>9.1f} MB")


@images_app.command("pull")
def images_pull(
    os_name: Optional[str] = typer.Argument(None, help="OS slug (e.g. ubuntu-server). Defaults to configured OS."),
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c"),
) -> None:
    """Pre-cache an OS image before deployment."""
    cfg = _load_config(config)
    if os_name is None:
        os_name = cfg.get("target", {}).get("os", "")
        if not os_name:
            typer.echo("[error] No OS specified and none configured.", err=True)
            raise typer.Exit(1)
    typer.echo(f"Pulling {os_name} image ...")
    try:
        dest = img.ensure_image(os_name, cfg)
        typer.echo(f"Cached: {dest}")
    except (RuntimeError, ValueError) as exc:
        typer.echo(f"[error] {exc}", err=True)
        raise typer.Exit(1)


@images_app.command("clean")
def images_clean(
    os_name: Optional[str] = typer.Argument(None, help="OS slug to remove. Omit to remove all."),
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c"),
    yes: bool = typer.Option(False, "--yes", "-y"),
) -> None:
    """Delete cached OS images. Pass an OS slug to delete only that OS."""
    cfg   = _load_config(config)
    cache = img.cache_dir_for(cfg)
    desc  = f"'{os_name}'" if os_name else "all"
    if not yes:
        typer.confirm(f"Delete {desc} images in {cache}?", abort=True)
    try:
        removed = img.clean_cache(cfg, os_name=os_name)
    except ValueError as exc:
        typer.echo(f"[error] {exc}", err=True)
        raise typer.Exit(1)
    typer.echo(f"Removed {removed} file(s).")


def _run_compose(cfg: dict, cwd: Path, *, up: bool) -> None:
    interface = cfg.get("provisioning_interface", "")
    seed_ip   = cfg.get("seed_ip") or _get_interface_ip(interface) or "192.168.100.1"

    env_vars = {
        "PROVISIONING_INTERFACE": interface,
        "DHCP_RANGE_START":       str(cfg.get("dhcp_range_start", "")),
        "DHCP_RANGE_END":         str(cfg.get("dhcp_range_end", "")),
        "DHCP_LEASE_TIME":        str(cfg.get("dhcp_lease_time", "12h")),
        "SEED_IP":                seed_ip,
        "IMAGE_CACHE_DIR":        str(img.cache_dir_for(cfg)),
    }

    cmd = ["docker", "compose", "up", "-d", "--build"] if up else ["docker", "compose", "down"]
    result = subprocess.run(
        cmd, cwd=cwd, capture_output=True, text=True,
        env={**os.environ, **env_vars},
    )
    if result.returncode != 0:
        typer.echo(f"[error] docker compose failed:\n{result.stderr}", err=True)
        raise typer.Exit(1)


def main() -> None:
    app()


if __name__ == "__main__":
    main()
