#!/usr/bin/env python3
"""VME — Velocitee Metal Provisioning Engine CLI."""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from string import Template
from typing import Optional

import typer
import yaml

from . import preflight as pf
from . import manifest as mf
from . import images as img
from . import setup as wizard
from .os_registry import OS_REGISTRY, cached_entries

app = typer.Typer(
    name="vme",
    help="Velocitee Metal Provisioning Engine — PXE-boot and unattended OS install.",
    add_completion=False,
)
images_app = typer.Typer(help="Manage cached OS images.")
app.add_typer(images_app, name="images")

_CONFIG_DEFAULT  = Path("vme-config.yml")
_REPO_ROOT       = Path(__file__).parent.parent
_LOG_DIR         = Path("~/.velocitee/logs").expanduser()
_MANIFEST_OUTDIR = _REPO_ROOT / "manifests" / "output"

_LINE = "═" * 60


def _load_config(config_path: Path) -> dict:
    if not config_path.exists():
        typer.echo(
            f"[error] Config file not found: {config_path}\n"
            "Run 'vme setup' to create one.",
            err=True,
        )
        raise typer.Exit(1)
    try:
        with open(config_path) as fh:
            return yaml.safe_load(fh) or {}
    except yaml.YAMLError as exc:
        typer.echo(f"[error] Config file is not valid YAML: {exc}", err=True)
        raise typer.Exit(1)


def _print_preflight(report: pf.PreflightReport) -> None:
    typer.echo()
    for result in report.results:
        icon = "  [pass]" if result.passed else "  [FAIL]"
        typer.echo(f"{icon}  {result.name:<16} {result.detail}")
        if not result.passed and result.fix:
            for line in result.fix.splitlines():
                typer.echo(f"         fix: {line}")
    typer.echo()


def _get_interface_ip(interface: str) -> Optional[str]:
    try:
        result = subprocess.run(
            ["ip", "addr", "show", interface],
            capture_output=True, text=True, timeout=5,
        )
        m = re.search(r"inet (\d+\.\d+\.\d+\.\d+)/", result.stdout)
        return m.group(1) if m else None
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None


def _assign_ip(interface: str, ip: str) -> None:
    if _get_interface_ip(interface):
        return
    typer.echo(f"  Assigning {ip}/24 to {interface} ...")
    result = subprocess.run(
        ["sudo", "ip", "addr", "add", f"{ip}/24", "dev", interface],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        typer.echo(
            f"[error] Could not assign IP to {interface}:\n{result.stderr}\n"
            f"Run manually: sudo ip addr add {ip}/24 dev {interface}",
            err=True,
        )
        raise typer.Exit(1)
    subprocess.run(["sudo", "ip", "link", "set", interface, "up"], capture_output=True)


def _generate_boot_ipxe(
    seed_ip: str,
    entries: list[tuple[str, str, str, Path]],
    default_slug: str,
) -> str:
    if not entries:
        return (
            "#!ipxe\n\n"
            f"set nginx http://{seed_ip}\n\n"
            "echo\necho  No OS images are cached on the seed machine.\n"
            "echo  Run: vme images pull <os-name>\n"
            "echo\nprompt --timeout 30\nexit 1\n"
        )

    lines: list[str] = [
        "#!ipxe",
        "# Generated by vme deploy — do not edit by hand.",
        "",
        f"set nginx http://{seed_ip}",
        "set sc:hex 3b",  # semicolon — iPXE treats ; as command separator so we can't write it literally
        "",
        "echo",
        "echo  ============================================================",
        "echo   VME — Velocitee Metal Provisioning Engine",
        "echo   Seed:  ${nginx}",
        "echo   MAC:   ${net0/mac}",
        "echo  ============================================================",
        "echo",
        "",
        ":menu",
        "menu VME Provisioning Menu",
    ]

    default_key = entries[0][1]
    for slug, key, label, _ in entries:
        if slug == default_slug:
            default_key = key
            break

    for _slug, key, label, _iso in entries:
        lines.append(f"item {key:<14} {label}")

    lines += [
        "item --gap --",
        "item exit           Exit (boot from local disk)",
        f"choose --default {default_key} --timeout 30 target || goto exit",
        "",
        "goto ${target}",
        "",
    ]

    for slug, key, label, iso in entries:
        meta = OS_REGISTRY.get(slug, {})
        boot_method = meta.get("boot_method", "sanboot")

        if boot_method == "kernel" and slug == "proxmox-ve":
            # Proxmox VE: kernel+initrd boot with HTTP ISO fetch.
            # pve_iso_url= is read by our initrd patch to download the ISO.
            # proxmox-start-auto-installer triggers the unattended installer.
            # The answer file is embedded directly in the initrd (from-iso mode).
            lines += [
                f":{key}",
                f"echo Booting {label} ...",
                f"kernel ${{nginx}}/boot/{slug}/vmlinuz",
                f"initrd ${{nginx}}/boot/{slug}/initrd",
                (
                    f"imgargs vmlinuz initrd=initrd"
                    f" ro ramdisk_size=16777216 rw quiet splash=silent"
                    f" pve_iso_url=${{nginx}}/images/{iso.name}"
                    f" proxmox-start-auto-installer"
                ),
                "boot || goto failed",
                "",
            ]
        elif boot_method == "kernel":
            # Ubuntu (and future Ubuntu-like): boot vmlinuz+initrd directly so
            # we can pass kernel cmdline args.
            # iso-url= is used instead of url= because cloud-init 24.x probes url= as a
            # datasource seed URL and re-downloads the ISO (~8 min delay). casper treats
            # iso-url= identically; cloud-init ignores it.
            lines += [
                f":{key}",
                f"echo Booting {label} ...",
                f"kernel ${{nginx}}/boot/{slug}/vmlinuz",
                f"initrd ${{nginx}}/boot/{slug}/initrd",
                (
                    f"imgargs vmlinuz initrd=initrd ip=dhcp"
                    f" iso-url=${{nginx}}/images/{iso.name}"
                    f" autoinstall ds=nocloud-net${{sc:string}}s=${{nginx}}/cloud-init/"
                ),
                "boot || goto failed",
                "",
            ]
        else:
            lines += [
                f":{key}",
                f"echo Booting {label} ...",
                f"echo Image: ${{nginx}}/images/{iso.name}",
                "echo",
                f"sanboot --no-describe ${{nginx}}/images/{iso.name} || goto failed",
                "",
            ]

    lines += [
        ":exit",
        "echo Exiting iPXE — attempting local disk boot.",
        "exit 0",
        "",
        ":failed",
        "echo",
        "echo Boot failed. Possible causes:",
        "echo   - Image not reachable at ${nginx}/images/",
        "echo   - Run: vme images list  (on the seed machine)",
        "echo",
        "echo Press any key to return to the menu.",
        "prompt --key s --timeout 10 || goto menu",
        "goto menu",
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Shell fragments injected into the Proxmox initrd /init at deploy time.
# Patch 1: inserted before  initrdisoimage="/proxmox.iso"
# Patch 2: inserted before  BASE_SQFS="/mnt/$PRODUCT_LC-base.squashfs"
# ---------------------------------------------------------------------------
_PVE_ISO_PATCH = (
    '# VME: fetch ISO from seed nginx on pve_iso_url= kernel param\n'
    '_pve_iso_url=\n'
    'for _par in $(cat /proc/cmdline); do\n'
    '    case $_par in\n'
    '        pve_iso_url=*) _pve_iso_url="${_par#pve_iso_url=}" ;;\n'
    '    esac\n'
    'done\n'
    'if [ -n "$_pve_iso_url" ]; then\n'
    # Load NIC drivers bundled from pve-installer.squashfs so VMware VMs
    # get a network interface.  Tries e1000, e1000e, and vmxnet3.
    # Verbose output so we can see whether modules are found and load cleanly.
    '    echo "VME: loading NIC drivers ..."\n'
    '    for _ko in'
    ' /lib/modules/*/kernel/drivers/net/ethernet/intel/e1000/e1000.ko'
    ' /lib/modules/*/kernel/drivers/net/ethernet/intel/e1000e/e1000e.ko'
    ' /lib/modules/*/kernel/drivers/net/vmxnet3/vmxnet3.ko; do\n'
    '        if [ -f "$_ko" ]; then\n'
    '            _err=$(/sbin/modprobe "$_ko" 2>&1) && echo "VME: loaded $(basename $_ko)"'
    ' || echo "VME: [warn] modprobe $(basename $_ko) failed: $_err"\n'
    '        else\n'
    '            echo "VME: [warn] module not found: $_ko"\n'
    '        fi\n'
    '    done\n'
    '    sleep 1\n'
    '    echo "VME: NICs in /sys/class/net: $(ls /sys/class/net/ 2>/dev/null | tr "\\n" " ")"\n'
    # Derive seed IP from the URL (http://SEED_IP/...) and assign a static
    # address in the same /24.  No DHCP needed — we know the network layout.
    '    _seed="${_pve_iso_url#http://}"; _seed="${_seed%%/*}"\n'
    '    _net="${_seed%.*}"\n'
    '    _my_ip="${_net}.99"\n'
    '    echo "VME: configuring network (seed=$_seed, self=$_my_ip) ..."\n'
    '    _iface=; _w=0\n'
    '    while [ -z "$_iface" ] && [ "$_w" -lt 10 ]; do\n'
    '        _iface=$(ls /sys/class/net/ 2>/dev/null | grep -v "^lo$" | head -1)\n'
    '        [ -z "$_iface" ] && sleep 1\n'
    '        _w=$((_w+1))\n'
    '    done\n'
    '    if [ -n "$_iface" ]; then\n'
    '        ip link set "$_iface" up 2>/dev/null\n'
    '        sleep 1\n'
    '        ip addr add "${_my_ip}/24" dev "$_iface" 2>/dev/null\n'
    '        ip route add default via "$_seed" 2>/dev/null\n'
    '        echo "VME: network ready on $_iface"\n'
    '    else\n'
    '        echo "VME: [warn] no NIC found after driver load, download will fail"\n'
    '    fi\n'
    '    echo "VME: fetching Proxmox ISO (timeout=60s) ..."\n'
    '    if wget -q --timeout=60 -O /proxmox.iso "$_pve_iso_url"; then\n'
    '        echo "VME: ISO downloaded OK"\n'
    '    else\n'
    '        echo "VME: [warn] ISO download failed (exit $?), will try block device scan"\n'
    '        rm -f /proxmox.iso\n'
    '    fi\n'
    'fi\n'
    '\n'
)

def _make_pve_ans_patch(answer_toml: str) -> str:
    """Return the shell fragment that replaces the stock cdrom bind mount.

    Mounts /cdrom as an overlay whose upper dir is on /mnt/.workdir — the
    installer's own tmpfs, which survives switch_root (unlike /tmp/ which is
    on the initrd root tmpfs and is freed by switch_root).

    Writes auto-installer-mode.toml (mode = "from-iso") and the fully-rendered
    answer.toml directly into the upper dir so no HTTP fetch is required from
    the installer.  Falls back to a plain bind mount when called without an
    answer (should never happen in normal use).
    """
    if not answer_toml:
        # No answer content — plain bind mount (no unattended install)
        return (
            '    if ! mount --bind /mnt /mnt/.installer-mp/cdrom; then\n'
            '        debugsh_err_reboot "bind mount cdrom failed"\n'
            '    fi\n'
        )

    return (
        '# VME: mount /cdrom as overlay; embed answer.toml (from-iso mode).\n'
        '# Upper dir on /mnt/.workdir (installer tmpfs) — survives switch_root.\n'
        '_vme_cdrom_done=0\n'
        'mkdir -p /mnt/.workdir/cdrom-upper /mnt/.workdir/cdrom-work\n'
        "printf 'mode = \"iso\"\\n'"
        ' > /mnt/.workdir/cdrom-upper/auto-installer-mode.toml\n'
        'cat > /mnt/.workdir/cdrom-upper/answer.toml << \'VME_ANSWER_EOF\'\n'
        + answer_toml.rstrip("\n") + "\n"
        + 'VME_ANSWER_EOF\n'
        'if mount -t overlay overlay'
        ' -o "lowerdir=/mnt,upperdir=/mnt/.workdir/cdrom-upper,workdir=/mnt/.workdir/cdrom-work"'
        ' /mnt/.installer-mp/cdrom 2>/dev/null; then\n'
        '    echo "VME: answer file injected (from-iso mode)"\n'
        '    _vme_cdrom_done=1\n'
        'else\n'
        '    echo "VME: [warn] cdrom overlay failed, auto-install will not be unattended"\n'
        'fi\n'
        'if [ "$_vme_cdrom_done" -eq 0 ]; then\n'
        '    if ! mount --bind /mnt /mnt/.installer-mp/cdrom; then\n'
        '        debugsh_err_reboot "bind mount cdrom failed"\n'
        '    fi\n'
        'fi\n'
    )


def _patch_proxmox_initrd(
    initrd_path: Path,
    nic_modules: list[tuple[Path, Path]],
    answer_toml: str = "",
) -> None:
    """Patch the Proxmox initrd to support PXE boot with unattended install.

    1. Bundle NIC driver .ko files (e1000, e1000e, vmxnet3) from the
       pve-installer squashfs so VMware VMs get a network interface in initrd.

    2. Inject two shell fragments into /init:

       a. Before  initrdisoimage="/proxmox.iso":
          Load NIC drivers, assign a static IP derived from pve_iso_url=,
          then wget the ISO to /proxmox.iso so the existing path finds it.

       b. Replaces  mount --bind /mnt /mnt/.installer-mp/cdrom:
          Mounts /cdrom as an overlay with auto-installer-mode.toml (from-iso)
          and the rendered answer.toml embedded in the upper dir.  The upper
          dir is on the installer's workdir tmpfs so it survives switch_root.
    """
    typer.echo("  Patching Proxmox initrd (NIC drivers + embedded answer) ...")
    work_dir = Path(tempfile.mkdtemp(prefix="vme-pve-"))
    try:
        rootfs   = work_dir / "rootfs"
        rootfs.mkdir()
        cpio_raw = work_dir / "initrd.cpio"
        cpio_new = work_dir / "initrd-patched.cpio"

        # 1. Decompress zstd → raw cpio
        r = subprocess.run(
            ["zstd", "-d", str(initrd_path), "-o", str(cpio_raw), "-f"],
            capture_output=True, text=True,
        )
        if r.returncode != 0:
            raise RuntimeError(f"zstd decompress failed: {r.stderr.strip()}")

        # 2. Extract cpio (device-node mknod errors in /dev are expected and harmless)
        with open(cpio_raw, "rb") as fh:
            subprocess.run(["cpio", "-id"], stdin=fh, cwd=rootfs, capture_output=True)

        # 3. Bundle NIC modules at the path the init patch expects.
        # nic_modules is list of (staged_src, dest_rel_inside_initrd) where
        # dest_rel is relative to the initrd root (e.g.
        # lib/modules/6.17.2-1-pve/kernel/drivers/net/ethernet/intel/e1000/e1000.ko).
        for src, dest_rel in nic_modules:
            dest = rootfs / dest_rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dest)
            typer.echo(f"  Bundled NIC module: {src.name} → {dest_rel}")

        # 4. Patch /init
        init_path = rootfs / "init"
        text = init_path.read_text()

        anchor1 = 'initrdisoimage="/proxmox.iso"'
        if anchor1 not in text:
            raise RuntimeError(f"Patch point 1 not found in Proxmox initrd /init ({anchor1!r})")
        text = text.replace(anchor1, _PVE_ISO_PATCH + anchor1, 1)

        # Anchor 2: replace the stock cdrom bind mount with our overlay patch.
        anchor2 = (
            '    if ! mount --bind /mnt /mnt/.installer-mp/cdrom; then\n'
            '        debugsh_err_reboot "bind mount cdrom failed"\n'
            '    fi\n'
        )
        if anchor2 not in text:
            raise RuntimeError(f"Patch point 2 not found in Proxmox initrd /init ({anchor2!r})")
        text = text.replace(anchor2, _make_pve_ans_patch(answer_toml), 1)

        init_path.write_text(text)

        # 5. Repack cpio and recompress with zstd
        r = subprocess.run(
            f"find . -print0 | cpio --null -o --format=newc | zstd -f -3 -o {cpio_new}",
            shell=True, cwd=rootfs, capture_output=True, text=True,
        )
        if r.returncode != 0:
            raise RuntimeError(f"cpio/zstd repack failed: {r.stderr.strip()}")

        shutil.copy2(cpio_new, initrd_path)
        typer.echo(
            f"  Proxmox initrd patched "
            f"({initrd_path.stat().st_size // (1024 ** 2)} MB, "
            f"NIC drivers + HTTP ISO + answer fetch enabled)."
        )
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)


def _extract_boot_files(iso_path: Path, boot_dir: Path, slug: str, answer_toml: str = "") -> None:
    """Mount an ISO and copy the kernel + initrd into boot_dir/slug/.

    Ubuntu's live initrd needs to be booted directly (not via sanboot) so we
    can pass url= and autoinstall params on the kernel cmdline. This extracts
    the right files from the ISO at deploy time.

    For Proxmox VE the initrd is additionally patched by _patch_proxmox_initrd
    to support HTTP ISO and answer-file delivery.
    """
    meta = OS_REGISTRY.get(slug, {})
    kernel_rel = meta.get("kernel_path", "casper/vmlinuz")
    initrd_rel  = meta.get("initrd_path", "casper/initrd")

    dest = boot_dir / slug
    vmlinuz = dest / "vmlinuz"
    initrd  = dest / "initrd"

    if vmlinuz.exists() and initrd.exists():
        return  # already extracted (and patched, for Proxmox) from a previous run

    dest.mkdir(parents=True, exist_ok=True)

    typer.echo(f"  Extracting boot files from {iso_path.name} ...")
    mnt = Path(tempfile.mkdtemp(prefix="vme-iso-"))
    try:
        result = subprocess.run(
            ["sudo", "mount", "-o", "loop,ro", str(iso_path), str(mnt)],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(f"Could not mount ISO: {result.stderr.strip()}")

        src_vmlinuz = mnt / kernel_rel
        src_initrd  = mnt / initrd_rel
        if not src_vmlinuz.exists() or not src_initrd.exists():
            raise RuntimeError(
                f"Expected {kernel_rel} and {initrd_rel} inside the ISO but couldn't find them."
            )

        shutil.copy2(src_vmlinuz, vmlinuz)
        shutil.copy2(src_initrd, initrd)
        # ISO files are often read-only; ensure we can patch the initrd below.
        vmlinuz.chmod(0o644)
        initrd.chmod(0o644)

        typer.echo(f"  Boot files extracted ({vmlinuz.stat().st_size // (1024**2)} MB kernel, "
                   f"{initrd.stat().st_size // (1024**2)} MB initrd).")

        # For Proxmox: extract NIC modules from pve-installer.squashfs while
        # the ISO is still mounted so we can bundle them into the initrd.
        # list of (staged_src, dest_rel_inside_initrd)
        nic_modules: list[tuple[Path, Path]] = []
        if slug == "proxmox-ve":
            sq_mnt = Path(tempfile.mkdtemp(prefix="vme-sq-"))
            try:
                r2 = subprocess.run(
                    ["sudo", "mount", "-o", "loop,ro",
                     str(mnt / "pve-installer.squashfs"), str(sq_mnt)],
                    capture_output=True, text=True,
                )
                if r2.returncode == 0:
                    for pattern in [
                        "usr/lib/modules/*/kernel/drivers/net/ethernet/intel/e1000/e1000.ko",
                        "usr/lib/modules/*/kernel/drivers/net/ethernet/intel/e1000e/e1000e.ko",
                        "usr/lib/modules/*/kernel/drivers/net/vmxnet3/vmxnet3.ko",
                    ]:
                        found = list(sq_mnt.glob(pattern))
                        if found:
                            # Copy out before unmounting — use dest as staging area
                            staged = dest / found[0].name
                            shutil.copy2(found[0], staged)
                            staged.chmod(0o644)
                            # Preserve path from lib/modules/... onward so the
                            # insmod glob inside the patched init resolves it.
                            dest_rel = found[0].relative_to(sq_mnt / "usr")
                            nic_modules.append((staged, dest_rel))
                else:
                    typer.echo("  [warn] Could not mount pve-installer.squashfs; "
                               "NIC modules will not be bundled.")
            finally:
                subprocess.run(["sudo", "umount", str(sq_mnt)], capture_output=True)
                sq_mnt.rmdir()
    finally:
        subprocess.run(["sudo", "umount", str(mnt)], capture_output=True)
        mnt.rmdir()

    if slug == "proxmox-ve":
        _patch_proxmox_initrd(initrd, nic_modules, answer_toml=answer_toml)


def _render_templates(cfg: dict, run_dir: Path) -> None:
    target    = cfg.get("target", {})
    interface = cfg["provisioning_interface"]
    seed_ip   = cfg.get("seed_ip") or _get_interface_ip(interface) or "192.168.100.1"
    os_name   = target.get("os", "")

    cache_dir = img.cache_dir_for(cfg)
    entries   = cached_entries(cache_dir)

    subs = {
        "PROVISIONING_INTERFACE": interface,
        "DHCP_RANGE_START":       cfg["dhcp_range_start"],
        "DHCP_RANGE_END":         cfg["dhcp_range_end"],
        "DHCP_LEASE_TIME":        cfg.get("dhcp_lease_time", "12h"),
        "SEED_IP":                seed_ip,
        "TARGET_HOSTNAME":        target.get("hostname", "node-01"),
        "TARGET_DOMAIN":          target.get("domain", "local"),
        "TARGET_IP":              target.get("ip", ""),
        "TARGET_PREFIX":          target.get("prefix", "24"),
        "TARGET_GATEWAY":         target.get("gateway", ""),
        "TARGET_NETMASK":         target.get("netmask", "255.255.255.0"),
        "TARGET_DNS":             target.get("dns", "8.8.8.8"),
        "TARGET_DISK":            target.get("disk", "/dev/sda"),
        "TARGET_NIC":             "eth0",
        "TARGET_TIMEZONE":        target.get("timezone", "UTC"),
        "TARGET_SSH_PUBLIC_KEY":  target.get("ssh_public_key", ""),
        "TARGET_ROOT_PASSWORD":   target.get("root_password", "changeme"),
        "TARGET_EMAIL":           target.get("email", "root@localhost"),
        "TARGET_PASSWORD_HASH":   target.get("password_hash", ""),
    }

    # Render the Proxmox answer file BEFORE boot file extraction so the rendered
    # content can be embedded directly into the patched initrd (from-iso mode).
    pve_answer_src = _REPO_ROOT / "targets" / "proxmox" / "answer.toml"
    pve_answer_rendered = ""
    if pve_answer_src.exists():
        pve_answer_rendered = Template(pve_answer_src.read_text()).safe_substitute(subs)
        pve_answer_dest = run_dir / "proxmox" / "answer.toml"
        pve_answer_dest.parent.mkdir(parents=True, exist_ok=True)
        pve_answer_dest.write_text(pve_answer_rendered)

    # For OSes that boot via kernel+initrd, extract those files from the ISO now
    # so nginx can serve them. The mount point needs sudo because loop devices do.
    boot_dir = run_dir / "boot"
    for slug, _key, _label, iso_path in entries:
        meta = OS_REGISTRY.get(slug, {})
        if meta.get("boot_method") == "kernel":
            ans = pve_answer_rendered if slug == "proxmox-ve" else ""
            _extract_boot_files(iso_path, boot_dir, slug, answer_toml=ans)

    boot_ipxe = _generate_boot_ipxe(seed_ip, entries, default_slug=os_name)
    boot_dest = run_dir / "ipxe" / "boot.ipxe"
    boot_dest.parent.mkdir(parents=True, exist_ok=True)
    boot_dest.write_text(boot_ipxe)

    templates = {
        _REPO_ROOT / "seed" / "dnsmasq" / "dnsmasq.conf":   run_dir / "dnsmasq" / "dnsmasq.conf",
        # answer.toml rendered above (before boot file extraction)
        _REPO_ROOT / "targets" / "ubuntu" / "preseed.cfg":  run_dir / "cloud-init" / "user-data",
        _REPO_ROOT / "targets" / "ubuntu" / "meta-data":    run_dir / "cloud-init" / "meta-data",
        _REPO_ROOT / "targets" / "ubuntu" / "vendor-data":  run_dir / "cloud-init" / "vendor-data",
    }

    for src, dest in templates.items():
        if not src.exists():
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(Template(src.read_text()).safe_substitute(subs))


def _fmt_bytes(raw: str) -> str:
    """Format a byte count string into a human-readable size."""
    try:
        b = int(raw)
    except (ValueError, TypeError):
        return raw
    if b >= 1024 ** 3:
        return f"{b / 1024 ** 3:.1f} GB"
    if b >= 1024 ** 2:
        return f"{b / 1024 ** 2:.1f} MB"
    return f"{b / 1024:.0f} KB"


# Events to surface in normal (non-verbose) mode.
# Each entry: (regex, display_template, deduplicate)
# {1}, {2} ... are replaced with capture groups; {1B} formats group 1 as bytes.
_LOG_EVENTS = [
    # ── PXE boot ─────────────────────────────────────────────────────────────
    (re.compile(r'DHCPDISCOVER\(\S+\)\s+([\da-fA-F:]{17})'),
     "Target on network       MAC {1}", True),
    (re.compile(r'DHCPACK\(\S+\)\s+(\d+\.\d+\.\d+\.\d+)\s+([\da-fA-F:]{17})\s*$'),
     "DHCP lease assigned     {1}  ({2})", True),
    (re.compile(r'sent /tftp/undionly\.kpxe to (\S+)'),
     "iPXE bootloader sent    to {1} via TFTP", True),
    (re.compile(r'"GET /ipxe/boot\.ipxe[^"]*" 200'),
     "Boot menu loaded        via HTTP — selecting OS", True),
    # ── Kernel + RAM disk (iPXE fetches these before handing off) ─────────────
    (re.compile(r'"GET /boot/[^/]+/vmlinuz[^"]*" 200 (\d+)'),
     "Kernel downloaded       {1B}", True),
    (re.compile(r'"GET /boot/[^/]+/initrd[^"]*" 200 (\d+)'),
     "RAM disk downloaded     {1B} — live installer booting", True),
    # ── ISO download (nginx log line appears when transfer completes) ─────────
    (re.compile(r'"GET /images/([^"]+\.iso)[^"]*" [25]\d\d (\d+)'),
     "OS image downloaded     {1}  ({2B})", True),
    # ── cloud-init autoinstall ────────────────────────────────────────────────
    (re.compile(r'"GET /cloud-init/user-data[^"]*" 200'),
     "Autoinstall config read — disk setup and packages starting", True),
    # ── early-commands hook (fires just before disk work in Ubuntu autoinstall)
    (re.compile(r'"GET /vme-install-running[^"]*"'),
     "Installer active        disk partitioning and apt in progress", True),
    # ── completion (handled separately — not printed here) ────────────────────
    (re.compile(r'vme-provision-complete'),
     None, False),
]


def _format_event(pattern: re.Pattern, template: str, line: str) -> str | None:
    m = pattern.search(line)
    if not m:
        return None
    result = template
    for i, g in enumerate(m.groups(), 1):
        result = result.replace(f"{{{i}B}}", _fmt_bytes(g or "0"))
        result = result.replace(f"{{{i}}}", g or "")
    return result


def _fmt_duration(seconds: float) -> str:
    m, s = divmod(int(seconds), 60)
    return f"{m}m {s:02d}s" if m else f"{s}s"


def _stream_deploy_logs(
    cwd: Path,
    log_path: Path,
    verbose: bool,
) -> tuple[bool, str | None]:
    """Stream compose logs. Returns (completed, mac_address).

    Normal mode: show one line per key milestone, suppress noise.
    Verbose mode: pass everything through.
    Full logs always written to log_path for troubleshooting.
    """
    proc = subprocess.Popen(
        ["docker", "compose", "logs", "-f", "--no-color"],
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )

    log_path.parent.mkdir(parents=True, exist_ok=True)
    completed  = False
    mac        = None
    shown: set[str] = set()

    try:
        with open(log_path, "w") as log_fh:
            for raw in proc.stdout:
                log_fh.write(raw)
                log_fh.flush()

                if verbose:
                    sys.stdout.write(raw)
                    sys.stdout.flush()
                else:
                    line = raw.strip()
                    ts   = datetime.now().strftime("%H:%M:%S")

                    for pattern, template, dedup in _LOG_EVENTS:
                        if not pattern.search(line):
                            continue
                        if template is None:
                            break
                        msg = _format_event(pattern, template, line)
                        if msg:
                            # Deduplicate on the template string (not the rendered message)
                            # so variable parts like IPs don't prevent dedup.
                            key = template
                            if dedup and key in shown:
                                break
                            shown.add(key)
                            typer.echo(f"  [{ts}]  {msg}")
                            # Capture MAC from DHCPACK line
                            if "DHCP lease" in msg:
                                m2 = re.search(r'\(([\da-fA-F:]{17})\)', msg)
                                if m2:
                                    mac = m2.group(1)
                        break

                # Completion signal — stop regardless of mode
                if "vme-provision-complete" in raw:
                    completed = True
                    break

    except KeyboardInterrupt:
        pass
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()

    return completed, mac


def _print_summary(
    cfg: dict,
    iso_path: Path,
    started_at: datetime,
    completed_at: datetime,
    manifest_path: Path,
    mac: str | None,
) -> None:
    target   = cfg.get("target", {})
    hostname = target.get("hostname", "")
    ip       = target.get("ip", "")
    os_name  = target.get("os", "")
    username = "root" if os_name == "proxmox-ve" else "ubuntu"
    duration = _fmt_duration((completed_at - started_at).total_seconds())

    typer.echo()
    typer.echo(_LINE)
    typer.echo(f"  Provisioning complete.")
    typer.echo()
    typer.echo(f"  Hostname:   {hostname}")
    typer.echo(f"  OS:         {iso_path.stem}")
    if mac:
        typer.echo(f"  MAC:        {mac}")
    typer.echo(f"  IP:         {ip}")
    typer.echo(f"  SSH user:   {username}")
    typer.echo(f"  Duration:   {duration}")
    typer.echo(f"  Manifest:   {manifest_path}")
    typer.echo(f"  Full logs:  {_LOG_DIR / manifest_path.stem}.log")
    typer.echo()
    typer.echo("  The machine has powered off.")
    typer.echo("  Before powering it on, fix the boot order so it boots from disk:")
    typer.echo()
    typer.echo("    VMware:        VM → Settings → Options → Boot → Hard Disk first")
    typer.echo("    Real hardware: Enter BIOS (F2 / Del / F12) → Boot Order → Hard Disk first")
    typer.echo()
    typer.echo("  Once booted:")
    typer.echo(f"    ssh {username}@{ip}")
    typer.echo(_LINE)


def _prompt_next_engine(manifest_path: Path) -> None:
    """Ask whether to hand off to VNE. Handles VNE not being installed."""
    typer.echo()
    typer.echo("  What next?")
    typer.echo("    [1]  Continue to VNE — configure networking")
    typer.echo("    [2]  Done — I'll connect manually or run other engines later")
    typer.echo()

    try:
        choice = input("  Choice [2]: ").strip() or "2"
    except (KeyboardInterrupt, EOFError):
        choice = "2"

    if choice != "1":
        typer.echo()
        typer.echo(f"  Manifest saved. Pass it to any engine with:")
        typer.echo(f"    vne setup --manifest {manifest_path}")
        typer.echo()
        return

    # Check if VNE is installed.
    if shutil.which("vne"):
        typer.echo()
        typer.echo("  Handing off to VNE ...")
        subprocess.run(["vne", "setup", "--manifest", str(manifest_path)])
    else:
        typer.echo()
        typer.echo("  VNE is not installed on this machine.")
        typer.echo("  To install VNE on the seed machine:")
        typer.echo("    curl -fsSL https://raw.githubusercontent.com/velocit-ee/core/main/vne/install.sh | bash")
        typer.echo()
        typer.echo(f"  Then run:")
        typer.echo(f"    vne setup --manifest {manifest_path}")
        typer.echo()


@app.command()
def setup(
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c", help="Path to write vme-config.yml"),
) -> None:
    """Guided setup wizard — creates your config file interactively."""
    wizard.run(config)


@app.command()
def preflight(
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c", help="Path to vme-config.yml"),
) -> None:
    """Run pre-flight checks without starting a deployment."""
    typer.echo("Running pre-flight checks ...")
    report = pf.run_all(config)
    _print_preflight(report)
    if report.passed:
        typer.echo("All checks passed. Ready to deploy.")
    else:
        typer.echo("[error] One or more checks failed.", err=True)
        raise typer.Exit(1)


@app.command()
def deploy(
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c", help="Path to vme-config.yml"),
    skip_preflight: bool = typer.Option(False, "--skip-preflight", help="Skip pre-flight checks."),
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Show full compose logs instead of filtered events."),
) -> None:
    """Provision a machine over PXE — runs unattended from power-on to shutdown."""
    cfg = _load_config(config)

    if not skip_preflight:
        typer.echo("Running pre-flight checks ...")
        report = pf.run_all(config)
        _print_preflight(report)
        if not report.passed:
            typer.echo("[error] Pre-flight failed. Aborting.", err=True)
            raise typer.Exit(1)
        typer.echo("Pre-flight passed.\n")

    interface = cfg.get("provisioning_interface", "")
    seed_ip   = cfg.get("seed_ip", "192.168.100.1")
    if interface:
        _assign_ip(interface, seed_ip)

    os_name: str = cfg.get("target", {}).get("os", "")
    typer.echo(f"Ensuring {os_name} image is cached ...")
    try:
        iso_path = img.ensure_image(os_name, cfg)
        typer.echo(f"  Image ready: {iso_path.name}\n")
    except (RuntimeError, ValueError) as exc:
        typer.echo(f"[error] {exc}", err=True)
        raise typer.Exit(1)

    run_dir = config.parent / "run"
    typer.echo("Preparing seed stack config ...")
    _render_templates(cfg, run_dir)

    typer.echo("Starting seed stack ...")
    _run_compose(cfg, config.parent, up=True)

    started_at = datetime.now(timezone.utc)
    hostname   = cfg.get("target", {}).get("hostname", "target")
    ts_label   = started_at.strftime("%Y%m%dT%H%M%SZ")
    log_path   = _LOG_DIR / f"deploy-{hostname}-{ts_label}.log"

    typer.echo()
    typer.echo(_LINE)
    typer.echo("  Seed stack is running.")
    typer.echo("  Power on the target machine now.")
    if verbose:
        typer.echo("  Showing full compose logs. Press Ctrl+C to stop.\n")
    else:
        typer.echo(f"  Watching for key events. Full logs → {log_path}")
        typer.echo("  Press Ctrl+C to stop manually.\n")

    completed, mac = _stream_deploy_logs(config.parent, log_path, verbose=verbose)

    completed_at = datetime.now(timezone.utc)

    typer.echo()
    typer.echo("Stopping seed stack ...")
    _run_compose(cfg, config.parent, up=False)

    if not completed:
        typer.echo("\nSeed stack stopped. Provisioning may not have completed.")
        typer.echo(f"Check the full logs at: {log_path}")
        raise typer.Exit(0)

    # Write manifest.
    try:
        manifest = mf.build_vme(
            cfg=cfg,
            iso_path=iso_path,
            mac=mac,
            started_at=started_at,
            completed_at=completed_at,
        )
        manifest_path = mf.write(manifest, _MANIFEST_OUTDIR)
    except (ValueError, Exception) as exc:
        typer.echo(f"[warn] Could not write manifest: {exc}", err=True)
        manifest_path = Path("(not written)")

    _print_summary(cfg, iso_path, started_at, completed_at, manifest_path, mac)
    _prompt_next_engine(manifest_path)


@app.command()
def status(
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c", help="Path to vme-config.yml"),
) -> None:
    """Show the current state of the seed stack."""
    result = subprocess.run(
        ["docker", "compose", "ps"],
        cwd=config.parent, capture_output=True, text=True,
    )
    if result.returncode != 0:
        typer.echo("[error] Could not query Docker Compose status.", err=True)
        raise typer.Exit(1)
    typer.echo(result.stdout)


@app.command()
def reset(
    config: Path        = typer.Option(_CONFIG_DEFAULT, "--config", "-c", help="Path to vme-config.yml"),
    include_config: bool = typer.Option(False, "--config-only", help="Also delete vme-config.yml (requires re-running vme setup)."),
    include_images: bool = typer.Option(False, "--images",      help="Also delete cached OS images (~3–8 GB)."),
    full:           bool = typer.Option(False, "--full",         help="Delete everything: stack, run/, config, and cached images."),
    yes:            bool = typer.Option(False, "--yes", "-y",    help="Skip confirmation prompt."),
) -> None:
    """Tear down VME state.

    By default removes the running seed stack and rendered run/ config,
    leaving vme-config.yml and cached OS images intact so the next
    'vme deploy' starts quickly.

    \b
    Flags:
      --config-only   also delete vme-config.yml  (re-run 'vme setup' after)
      --images        also delete cached OS images (~3-8 GB freed)
      --full          delete everything (stack + run/ + config + images)
    """
    if full:
        include_config = True
        include_images = True

    cwd   = config.parent
    parts = ["seed stack containers and volumes", "rendered run/ config"]
    if include_config:
        parts.append("vme-config.yml  (requires re-running 'vme setup')")
    if include_images:
        parts.append("cached OS images")

    if not yes:
        typer.echo("This will remove:")
        for p in parts:
            typer.echo(f"  • {p}")
        typer.echo()
        typer.confirm("Continue?", abort=True)

    # Load config now, before potentially deleting it, so image cache path is known.
    cfg_dict = _load_config(config) if (include_images and config.exists()) else {}

    typer.echo("Stopping seed stack ...")
    subprocess.run(["docker", "compose", "down", "--volumes"], cwd=cwd, capture_output=True)

    # The vme-ipxe-build image is NOT removed — it contains only compiled iPXE
    # binaries with no per-deployment state. Keeping it avoids a full rebuild
    # (and the Docker Hub pull it requires) on every reset+deploy cycle.

    run_dir = cwd / "run"
    if run_dir.exists():
        typer.echo("Clearing run/ ...")
        shutil.rmtree(run_dir)

    if include_config and config.exists():
        config.unlink()
        typer.echo("Deleted vme-config.yml.")

    if include_images and cfg_dict:
        removed = img.clean_cache(cfg_dict)
        typer.echo(f"Removed {removed} cached image file(s).")

    next_cmd = "vme setup" if include_config else "vme deploy"
    typer.echo(f"\nReset complete. Run '{next_cmd}' to start fresh.")


@images_app.command("list")
def images_list(
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c"),
) -> None:
    """List cached OS images."""
    cfg    = _load_config(config)
    cached = img.list_cached(cfg)
    if not cached:
        typer.echo("No images cached yet. Run 'vme images pull <os>' to download.")
        typer.echo(f"  Available: {', '.join(OS_REGISTRY)}")
        return
    typer.echo(f"  {'OS':<16} {'Filename':<46} {'Size':>10}")
    typer.echo("  " + "-" * 74)
    for entry in cached:
        typer.echo(f"  {entry['os']:<16} {entry['filename']:<46} {entry['size_mb']:>9.1f} MB")


@images_app.command("pull")
def images_pull(
    os_name: Optional[str] = typer.Argument(None, help="OS slug (e.g. ubuntu-server). Defaults to configured OS."),
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c"),
) -> None:
    """Pre-cache an OS image before deployment."""
    cfg = _load_config(config)
    if os_name is None:
        os_name = cfg.get("target", {}).get("os", "")
        if not os_name:
            typer.echo("[error] No OS specified and none configured.", err=True)
            raise typer.Exit(1)
    typer.echo(f"Pulling {os_name} image ...")
    try:
        dest = img.ensure_image(os_name, cfg)
        typer.echo(f"Cached: {dest}")
    except (RuntimeError, ValueError) as exc:
        typer.echo(f"[error] {exc}", err=True)
        raise typer.Exit(1)


@images_app.command("clean")
def images_clean(
    os_name: Optional[str] = typer.Argument(None, help="OS slug to remove. Omit to remove all."),
    config: Path = typer.Option(_CONFIG_DEFAULT, "--config", "-c"),
    yes: bool = typer.Option(False, "--yes", "-y"),
) -> None:
    """Delete cached OS images. Pass an OS slug to delete only that OS."""
    cfg   = _load_config(config)
    cache = img.cache_dir_for(cfg)
    desc  = f"'{os_name}'" if os_name else "all"
    if not yes:
        typer.confirm(f"Delete {desc} images in {cache}?", abort=True)
    try:
        removed = img.clean_cache(cfg, os_name=os_name)
    except ValueError as exc:
        typer.echo(f"[error] {exc}", err=True)
        raise typer.Exit(1)
    typer.echo(f"Removed {removed} file(s).")


def _run_compose(cfg: dict, cwd: Path, *, up: bool) -> None:
    interface = cfg.get("provisioning_interface", "")
    seed_ip   = cfg.get("seed_ip") or _get_interface_ip(interface) or "192.168.100.1"

    env_vars = {
        "PROVISIONING_INTERFACE": interface,
        "DHCP_RANGE_START":       str(cfg.get("dhcp_range_start", "")),
        "DHCP_RANGE_END":         str(cfg.get("dhcp_range_end", "")),
        "DHCP_LEASE_TIME":        str(cfg.get("dhcp_lease_time", "12h")),
        "SEED_IP":                seed_ip,
        "IMAGE_CACHE_DIR":        str(img.cache_dir_for(cfg)),
    }

    cmd = ["docker", "compose", "up", "-d", "--build"] if up else ["docker", "compose", "down"]
    result = subprocess.run(
        cmd, cwd=cwd, capture_output=True, text=True,
        env={**os.environ, **env_vars},
    )
    if result.returncode != 0:
        typer.echo(f"[error] docker compose failed:\n{result.stderr}", err=True)
        raise typer.Exit(1)


def main() -> None:
    app()


if __name__ == "__main__":
    main()
